### ISSUE TITLE
Duplicate key in en.json

### ISSUE THREAD

**Issue by phenomen** [foundryvtt-dcc/dcc#347]
`FleetingLuckSpendTitle` key is used for two different strings and it cause some issues when importing into translation software.

**Comment by algnc** [comment]
Fixed in #348

**Comment by mooped** [comment]
I just spotted this, and it seems that the linked change made alterations to Elf Immunities only. The duplicate Fleeting Luck key is still present.

**Comment by algnc** [comment]
hopefully fixed in #349
